<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <RevitYear Condition="'$(RevitYear)' == ''">2024</RevitYear>
    <OutputPath>bin\$(Configuration)\$(RevitYear)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RevitYear)' &lt;= '2024'">
		<TargetFramework>net48</TargetFramework>
		<DefineConstants>$(DefineConstants);REVIT$(RevitYear)</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(RevitYear)' &gt;= '2025'">
		<TargetFramework>net8.0-windows</TargetFramework>
		<DefineConstants>$(DefineConstants);REVIT$(RevitYear)</DefineConstants>
	</PropertyGroup>

  <ItemGroup Condition="'$(RevitYear)' != ''">
    <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="$(RevitYear).*" PrivateAsses="All" ExcludeAssets="Runtime" />
  </ItemGroup>

</Project>
